### ISSUE TITLE
Update Basilisk add-on to 2.21.1

### ISSUE THREAD

**Issue by Chirunos** [RealRaven2000/ZombieKeys#3]
As you can see [here](https://addons.basilisk-browser.org/addon/zombiekeys/), the add-on is still on 2.21

**Comment by RealRaven2000** [comment]
the information there is a little outdated - I guess this must have been grandfathered in from Palemoon...
I have worked a little bit on updating to modern versions of Thunderbird, but didn't go as far as porting the Settings UI, as the version is a little unstable. Not even sure when & where I released 2.21, it's been a while... it's missing in my releases folder so I need to check where the Tb68 branch is. Also I have no idea what the platform (Gecko) version of Basilisk 2023.01.26 is. Is it 26? 

That would be heck'a old. I was hoping it would be 54 or 68... Mozilla Code has moved so far apart from this...

**Comment by RealRaven2000** [comment]
I uploaded the new version - but the whole site is a little dubious. I could add the version but there is no textbox for entering a change log. The version is released to the basilisk website directly, no review process, which suggests that the add-ons there are not vetted / reviewed - a big angle for hackers and malicious actors. I guess they probably wouldn't have manpower to get voluntary Add-on reviewers. Also the UI of Basilisk is a little outdated - it's not dark mode aware so that I cannot read any menu items (top menu) or inactive tabs.

Version history below (luckily I make notes in the main script file `zombiekeys-overlay.js`):

Version 2.21.1 - 08/04/2019
	Made install.rdf compatible with Thunderbird 60
	Removed donation tab when updating ZombieKeys.
	Removed obsolete Addon Manager interface.

If I resume development on ZombieKeys it will definitely be on the new branch (Zombiekeys 3.0) most likely with a minimum version of Thunderbird 78. Firefox doesn't currently support "experimental" Add-ons so this would be a mail only Add-on on that branch going forward.

**Comment by Chirunos** [comment]
>Also I have no idea what the platform (Gecko) version of Basilisk 2023.01.26 is. Is it 26?

According to `about:support`, the user agent is `Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Goanna/6.0 Firefox/102.0 Basilisk/20230126` and the version is `52.9.2023.01.26 (64-bit)`. This can perhaps give you a hint about that
>I could add the version but there is no textbox for entering a change log.

I'm pretty sure there's no way you can put the changelog directly on the website
>I guess they probably wouldn't have manpower to get voluntary Add-on reviewers

Probably, since Basilisk Browser is currently a small project and there are not many people to be part of an add-on review team
